import requests

BASE_URL = "http://localhost:8000"

# 1. Index a new document (embedding will be auto-generated by Meilisearch)
index_payload = {
    "id": 2,
    "title": "AI-Powered Search Guide",
    "content": "This guide explains how to use AI-powered search with Meilisearch.",
}
resp = requests.post(f"{BASE_URL}/index", json=index_payload)
print("Index response:", resp.json())

# 2. Search for similar documents (hybrid search, semanticRatio=1.0 for pure semantic)
search_payload = {
    "query": "How to use AI search?",
    "top_k": 3,
    "semantic_ratio": 1.0
}
resp = requests.post(f"{BASE_URL}/search", json=search_payload)
print("Search response:", resp.status_code, resp.text)
